### ISSUE TITLE
Demo data 

### ISSUE THREAD

**Issue by dras2255** [evanseitz/ManifoldEM_Python#4]
I am trying to work through the ManifoldEM (beta) python demo. It seems that the demo link at the beginning of the manual is not functional and so I cannot find the alignment (RyR1GCs_clustRem.star) or image stack (RyR1GC_clustRem.mrcs) files. I am wondering if a new link to the source of this data could be provided. Thanks a lot!

**Comment by evanseitz** [comment]
Hi @dras2255, you should be able to use the mirror link in the demo PDF –– please use the link in the footnote on that same page:
https://github.com/evanseitz/ManifoldEM_Python/blob/main/ManifoldEM_Manual_Beta.pdf

(You might need to download the PDF locally, outside of the GitHub viewer, to click the link)

**Comment by dras2255** [comment]
Hello Evan,

Thank you very much for the response. I should have seen this
mirror download so my apologies. After downloading the RyR1_GC demo set
from google drive I was not able to locate the .star alignment file. Could
you please advise?

Thank you for the help.

Damien

**Comment by evanseitz** [comment]
The Google Drive contains a zip file "RyR1_GCs_demo.zip". When this file is unzipped, you will find it contains:
1. RyR1GCs_clustRem.mrcs
2. RyR1GCs_clustRem.star, the alignment file

**Comment by dras2255** [comment]
These are the only two files that are present when the folder is unzipped: 

RyR1_AvgVol_Binned.mrc
RyR1GCs_clustRem.mrcs


![54D3DC05-4F73-4C38-A34A-2C951F616635_4_5005_c](https://github.com/user-attachments/assets/44231880-a82a-42aa-895c-01edf3d1957e)

**Comment by evanseitz** [comment]
You may have an incomplete download (?). I just downloaded the zip file from the drive, unzipped it, and see the following:

<img width="211" alt="Screenshot 2024-11-22 at 2 05 48 PM" src="https://github.com/user-attachments/assets/da70a9ea-6492-4179-8a08-749a8f076b7b">

Regardless, I've added the .star file manually to the demo folder in the repo:
https://github.com/evanseitz/ManifoldEM_Python/tree/main/demo

**Comment by dras2255** [comment]
I have tried it multiple time so I am not sure what the issue is. I was able to download it from the repo. Thank you for your help.

**Comment by dras2255** [comment]
I have downloaded multiple times so I am not sure what the issue is. I was able to get it form the repo. Thanks for your help.
